
import type { Metadata } from "next";
import { montserrat, playfairDisplay } from "@/lib/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",   
  description: "Generated by create next app",
};

import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${playfairDisplay.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
